Changed yaml load to safe load due to error
If run as it was in Google Colab, one got the following error:

"TypeError: load() missing 1 required positional argument: 'Loader'"

This proposed change fixes that error, allowing it to run correctly.